# Generated by Django 3.2.3 on 2021-12-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211214_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualleave',
            old_name='update_on',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='update_on',
            new_name='updated_on',
        ),
    ]
