# Generated by Django 3.2.3 on 2021-12-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211214_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualleave',
            name='month',
            field=models.DateField(),
        ),
    ]
