# Generated by Django 3.2.3 on 2021-12-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_attendence_working_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualleave',
            old_name='name',
            new_name='holiday_name',
        ),
    ]
