# Generated by Django 3.2.3 on 2021-12-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_name_annualleave_holiday_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualleave',
            name='month',
            field=models.IntegerField(),
        ),
    ]
