# Generated by Django 3.2.3 on 2021-12-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_annualleave_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualleave',
            options={'ordering': ['-created_on']},
        ),
    ]
